version: "3"

services:
  airdrum:
    image: airdrum:latest
    build: .
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    devices:
      - /dev/video0:/dev/video0
