version: "3"

services:
  app:
    image: airdrum:latest
    build: airdrum_app
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - /dev/video0:/dev:/video0